image: Ubuntu2004
stack: jdk 11

branches:
  only:
    - main

build: off

install:
  # Даем права на выполнение gradlew (как в подсказке)
  - chmod +x gradlew

build_script:
  # 1. Запускаем SUT в фоновом режиме (&)
  - java -jar ./artifacts/app-mbank.jar &
  # 2. Ждем чтобы сервис успел запуститься
  - sleep 20
  # 3. Проверяем что сервис запустился (должен показать процесс на порту 9999)
  - netstat -tulpn | grep 9999 || echo "Service check - port 9999"
  # 4. Запускаем тесты БЕЗ ignoreFailures - чтобы сборка ПАДАЛА при неудачных тестах
  - ./gradlew test --info