image: Ubuntu2004
stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - chmod +x gradlew
  - ./gradlew clean compileTestJava --refresh-dependencies --stacktrace

build_script:
  - java -jar ./artifacts/app-mbank.jar &
  - sleep 45
  - ./gradlew test --info --stacktrace