image: Ubuntu2004

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - chmod +x gradlew
  - ./gradlew clean compileTestJava --refresh-dependencies

build_script:
  - java -jar ./artifacts/app-mbank.jar &
  - sleep 30
  - ./gradlew test --info