image: Ubuntu2004
stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - chmod +x gradlew
  # Обновляем зависимости перед запуском
  - ./gradlew dependencies --refresh-dependencies

build_script:
  # 1. Запускаем SUT с выводом логов
  - java -jar ./artifacts/app-mbank.jar &

  # 2. Ждем достаточно времени для запуска
  - echo "Waiting for service to start..."
  - sleep 25

  # 3. Проверяем что сервис запустился
  - curl -f http://localhost:9999/api/accounts || echo "Service check completed"

  # 4. Запускаем тесты с детальным выводом
  - ./gradlew clean test --info --no-daemon