image: Ubuntu2004
stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - chmod +x gradlew

build_script:
  # Останавливаем любой процесс на порту 9999 (для CI)
  - pkill -f "java.*app-mbank" || true
  # Запускаем SUT
  - java -jar ./artifacts/app-mbank.jar &
  # Ждем
  - sleep 15
  # Проверяем доступность
  - curl -f http://localhost:9999/ || echo "Service check"
  # Запускаем тесты
  - ./gradlew clean test --info